name: medical_ai_frontend
description: "AI-Powered Medical Document Query Tool for Malaysian Healthcare"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    

  # UI Components
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # State Management
  provider: ^6.1.2
  get: ^4.6.6
  
  # HTTP & API
  dio: ^5.4.3+1
  http: ^1.2.1
  
  # File Handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  
  # Charts & Visualization
  fl_chart: ^0.68.0
  timeline_tile: ^2.0.0
  
  # Voice & Audio
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  
  # Advanced UI
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Animation
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  
  # Web specific
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/background.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
